name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup MySQL 8.0
        uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0
          database: devswap

      - name: Config MySQL
        run: |
          mysqladmin -u root password '12345678'
          exit;

      - name: npm install, build, and test
        run: |
          npm ci
          cp env/.env.sample env/.env
          git submodule update --init
          ./copy_contracts.sh
          npx hardhat compile
          npx hardhat test
          echo 'everything is done'
        env:
          CI: true
